version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: animalession_store
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d animalession_store"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    image: shreyammaity/animalession:latest
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: animalession_store
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_URL: https://${DEPLOYMENT_HOST}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.animalession.rule=Host(`${DEPLOYMENT_HOST}`)"
      - "traefik.http.routers.animalession.entrypoints=websecure"
      - "traefik.http.routers.animalession.tls=true"
      - "traefik.http.routers.animalession.tls.certresolver=leresolver"
      - "traefik.http.services.animalession.loadbalancer.server.port=3000"

networks:
  internal:
  traefik:
    external: true

volumes:
  pgdata:
